Get receipt endpoint
sunb26/xat pull request #162
Opened 2024-04-03 21:20 UTC by sunb26

- The money module is to implement a representation of currency for converting from PostgreSQL "money" type to Go. Apparently the float64 in Go will lose precision so I am using a struct to represent dollars and cents as integer so no info is lost.

2024-04-03 22:52 UTC, Lev1ty requested changes

2024-04-03 22:52 UTC, Lev1ty commented on utils/money.go
Why not use an external library to handle money? Also do we need to ever convert it from string form to numeric? Could it be sent as-is to frontend and frontend also uses an external library to handle money strings? Typically money strings are not converted to and from numeric manually, and not hand-rolled utils with no tests to work with it

2024-04-04 03:08 UTC, sunb26 commented on utils/money.go
I can send the string directly to the FE if that works. I had coded the money manually because I wanted to avoid introducing another dependency because I figured it would be simple to implement.

2024-04-08 00:00 UTC, Lev1ty approved these changes

2024-04-08 18:10 UTC, merged